name: pr-check

on:
  pull_request_target:
    branches:
      - main
      - 'releases/*'

jobs:
    build:
      environment: Automation test
      runs-on: windows-latest
      steps:
      - name: Checkout from PR branch  
        uses: actions/checkout@v2
        with: 
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: installing node_modules
        run: npm install 
       
      - name: Build GitHub Action
        run: npm run build
  
